[phases.setup]
nixPkgs = ['php82', 'php82Extensions.intl', 'php82Extensions.mbstring']

[phases.install]
cmds = ['composer install --no-dev --optimize-autoloader --no-interaction']

[start]
cmd = 'php -S 0.0.0.0:${PORT:-8080} -t public'
